// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
        "aws_cognito_identity_pool_id": "us-west-2:9623c1f5-d417-48bd-8e33-b9d31831de8c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_LmasW1x2k",
    "aws_user_pools_web_client_id": "48t2p697rspus71buu5c621r40",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://2oggptxkbfgqtpuqo6rctgrgna.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photoalbumsf1d615ef77494ec9941a26bf5ccd5901210628-master",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
